version: "2"

services:
  reviver:
    build: .
    env_file: 
    - .env
    restart: always
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: reviver
      POSTGRES_DB: reviver
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
