version: "2"

services:
  reviver:
    build: .
    env_file: .env
    environment:
      DB_DSN: postgresql://postgres:postgres@postgres:5432/reviver
    restart: always
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reviver
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
